version: '3'
services:
    ganache:
        image: trufflesuite/ganache-cli
        ports:
            - 7545:7545
        command: -p 7545 -i 5777 -b 1 -a 100 --gasLimit 0x7FFFFFFF --gasPrice 1 -m "vanish junk genuine web seminar cook absurd royal ability series taste method identify elevator liquid"
    management-service-mainnet:
        build:
            context: ""
            dockerfile: Dockerfile-management-service
            args:
                - EthereumGenesisContract=0x5cd0D270C30EDa5ADa6b45a5289AFF1D425759b3
                - EthereumEndpoint=http://ganache:7545
                - EthereumFirstBlock=0
        ports:
            - 7666:8080
    contract-deployer:
        image: node
        working_dir: /usr/src/app
        volumes:
        -   ./.:/usr/src/app
        environment:
            ETHEREUM_URL: http://ganache:7545
        command: ./init-contracts.sh


