version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.17.0    
    steps:
      - checkout
      - run: ./.circleci/build.sh
      - store_artifacts:
          path: /home/circleci/.npm/_logs

workflows:
  build:
    jobs:      
      - build:
          filters:
            branches:
              only: master

          
