version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    machine: true
    steps:
      - checkout
      - node/install:
          node-version: "14.17.5"
      - run: ./.circleci/build.sh
      - store_artifacts:
          path: /.npm/_logs
          destination: npm_logs
      - store_artifacts:
          path: /_logs
          destination: npm_logs2

workflows:
  build:
    jobs:
      - build
