version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    machine: true
    steps:
      - checkout
      - node/install:
          node-version: "10.17.0"
      - run: ./.circleci/build.sh
      - store_artifacts:
          path: /home/circleci/.npm/_logs

workflows:
  build:
    jobs:
      - build
