version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    machine: true
    steps:
      - checkout
      - node/install:
          node-version: "14.17.5"
      - run: ./.circleci/build.sh
      - run: mv /home/circleci/.npm/_logs/* $CIRCLE_ARTIFACTS

workflows:
  build:
    jobs:
      - build
