/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js';
import { ContractOptions } from 'web3-eth-contract';
import { EventLog } from 'web3-core';
import { EventEmitter } from 'events';
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from './types';

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type ClientSet = ContractEventLog<{
  client: string;
  0: string;
}>;
export type EmergencyWithdrawal = ContractEventLog<{
  addr: string;
  0: string;
}>;
export type FunctionalOwnershipTransferred = ContractEventLog<{
  previousFunctionalOwner: string;
  newFunctionalOwner: string;
  0: string;
  1: string;
}>;
export type FundsAddedToPool = ContractEventLog<{
  added: string;
  total: string;
  0: string;
  1: string;
}>;
export type MaxAnnualRateSet = ContractEventLog<{
  maxAnnualRate: string;
  0: string;
}>;
export type MigrationOwnershipTransferred = ContractEventLog<{
  previousMigrationOwner: string;
  newMigrationOwner: string;
  0: string;
  1: string;
}>;
export type OutstandingTokensReset = ContractEventLog<{}>;

export interface ProtocolWallet extends BaseContract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions): ProtocolWallet;
  clone(): ProtocolWallet;
  methods: {
    /**
     * Allows the pendingFunctionalOwner address to finalize the transfer.
     */
    claimFunctionalOwnership(): NonPayableTransactionObject<void>;

    /**
     * Allows the pendingMigrationOwner address to finalize the transfer.
     */
    claimMigrationOwnership(): NonPayableTransactionObject<void>;

    client(): NonPayableTransactionObject<string>;

    /**
     * Returns the address of the current functionalOwner.
     */
    functionalOwner(): NonPayableTransactionObject<string>;

    /**
     * Returns true if the caller is the current functionalOwner.
     */
    isFunctionalOwner(): NonPayableTransactionObject<boolean>;

    /**
     * Returns true if the caller is the current migrationOwner.
     */
    isMigrationOwner(): NonPayableTransactionObject<boolean>;

    /**
     * Returns the address of the current migrationOwner.
     */
    migrationOwner(): NonPayableTransactionObject<string>;

    /**
     * Leaves the contract without functionalOwner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current functionalOwner.     * NOTE: Renouncing functionalOwnership will leave the contract without an functionalOwner, thereby removing any functionality that is only available to the functionalOwner.
     */
    renounceFunctionalOwnership(): NonPayableTransactionObject<void>;

    /**
     * Leaves the contract without migrationOwner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current migrationOwner.     * NOTE: Renouncing migrationOwnership will leave the contract without an migrationOwner, thereby removing any functionality that is only available to the migrationOwner.
     */
    renounceMigrationOwnership(): NonPayableTransactionObject<void>;

    token(): NonPayableTransactionObject<string>;

    /**
     * Allows the current functionalOwner to set the pendingOwner address.
     * @param newFunctionalOwner The address to transfer functionalOwnership to.
     */
    transferFunctionalOwnership(newFunctionalOwner: string): NonPayableTransactionObject<void>;

    /**
     * Allows the current migrationOwner to set the pendingOwner address.
     * @param newMigrationOwner The address to transfer migrationOwnership to.
     */
    transferMigrationOwnership(newMigrationOwner: string): NonPayableTransactionObject<void>;

    /**
     * Returns the address of the underlying staked token.
     * @returns IERC20 The address of the token.
     */
    getToken(): NonPayableTransactionObject<string>;

    /**
     * Returns the address of the underlying staked token.
     * @returns IERC20 The address of the token.
     */
    getBalance(): NonPayableTransactionObject<string>;

    /**
     * Transfers the given amount of orbs tokens form the sender to this contract an update the pool.
     */
    topUp(amount: number | string): NonPayableTransactionObject<void>;

    /**
     * withdraws from the pool to a spender, limited by the pool's MaxRate. A maximum of MaxRate x time period since the last Orbs transfer may be transferred out.
     */
    withdraw(amount: number | string): NonPayableTransactionObject<void>;

    /**
     * Sets a new transfer rate for the Orbs pool.
     */
    setMaxAnnualRate(_annualRate: number | string): NonPayableTransactionObject<void>;

    /**
     * Sets a new transfer rate for the Orbs pool.
     */
    resetOutstandingTokens(): NonPayableTransactionObject<void>;

    /**
     * transfer the entire pool's balance to a new wallet.
     */
    emergencyWithdraw(): NonPayableTransactionObject<void>;

    /**
     * sets the address of the new contract
     */
    setClient(_client: string): NonPayableTransactionObject<void>;
  };
  events: {
    ClientSet(cb?: Callback<ClientSet>): EventEmitter;
    ClientSet(options?: EventOptions, cb?: Callback<ClientSet>): EventEmitter;

    EmergencyWithdrawal(cb?: Callback<EmergencyWithdrawal>): EventEmitter;
    EmergencyWithdrawal(options?: EventOptions, cb?: Callback<EmergencyWithdrawal>): EventEmitter;

    FunctionalOwnershipTransferred(cb?: Callback<FunctionalOwnershipTransferred>): EventEmitter;
    FunctionalOwnershipTransferred(options?: EventOptions, cb?: Callback<FunctionalOwnershipTransferred>): EventEmitter;

    FundsAddedToPool(cb?: Callback<FundsAddedToPool>): EventEmitter;
    FundsAddedToPool(options?: EventOptions, cb?: Callback<FundsAddedToPool>): EventEmitter;

    MaxAnnualRateSet(cb?: Callback<MaxAnnualRateSet>): EventEmitter;
    MaxAnnualRateSet(options?: EventOptions, cb?: Callback<MaxAnnualRateSet>): EventEmitter;

    MigrationOwnershipTransferred(cb?: Callback<MigrationOwnershipTransferred>): EventEmitter;
    MigrationOwnershipTransferred(options?: EventOptions, cb?: Callback<MigrationOwnershipTransferred>): EventEmitter;

    OutstandingTokensReset(cb?: Callback<OutstandingTokensReset>): EventEmitter;
    OutstandingTokensReset(options?: EventOptions, cb?: Callback<OutstandingTokensReset>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: 'ClientSet', cb: Callback<ClientSet>): void;
  once(event: 'ClientSet', options: EventOptions, cb: Callback<ClientSet>): void;

  once(event: 'EmergencyWithdrawal', cb: Callback<EmergencyWithdrawal>): void;
  once(event: 'EmergencyWithdrawal', options: EventOptions, cb: Callback<EmergencyWithdrawal>): void;

  once(event: 'FunctionalOwnershipTransferred', cb: Callback<FunctionalOwnershipTransferred>): void;
  once(
    event: 'FunctionalOwnershipTransferred',
    options: EventOptions,
    cb: Callback<FunctionalOwnershipTransferred>,
  ): void;

  once(event: 'FundsAddedToPool', cb: Callback<FundsAddedToPool>): void;
  once(event: 'FundsAddedToPool', options: EventOptions, cb: Callback<FundsAddedToPool>): void;

  once(event: 'MaxAnnualRateSet', cb: Callback<MaxAnnualRateSet>): void;
  once(event: 'MaxAnnualRateSet', options: EventOptions, cb: Callback<MaxAnnualRateSet>): void;

  once(event: 'MigrationOwnershipTransferred', cb: Callback<MigrationOwnershipTransferred>): void;
  once(
    event: 'MigrationOwnershipTransferred',
    options: EventOptions,
    cb: Callback<MigrationOwnershipTransferred>,
  ): void;

  once(event: 'OutstandingTokensReset', cb: Callback<OutstandingTokensReset>): void;
  once(event: 'OutstandingTokensReset', options: EventOptions, cb: Callback<OutstandingTokensReset>): void;
}
