/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js';
import { ContractOptions } from 'web3-eth-contract';
import { EventLog } from 'web3-core';
import { EventEmitter } from 'events';
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from './types';

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type ContractRegistryAddressUpdated = ContractEventLog<{
  addr: string;
  0: string;
}>;
export type FunctionalOwnershipTransferred = ContractEventLog<{
  previousFunctionalOwner: string;
  newFunctionalOwner: string;
  0: string;
  1: string;
}>;
export type GenesisRefTimeDelayChanged = ContractEventLog<{
  newGenesisRefTimeDelay: string;
  0: string;
}>;
export type Locked = ContractEventLog<{}>;
export type MigrationOwnershipTransferred = ContractEventLog<{
  previousMigrationOwner: string;
  newMigrationOwner: string;
  0: string;
  1: string;
}>;
export type Payment = ContractEventLog<{
  vcid: string;
  by: string;
  amount: string;
  tier: string;
  rate: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
}>;
export type SubscriberAdded = ContractEventLog<{
  subscriber: string;
  0: string;
}>;
export type SubscriberRemoved = ContractEventLog<{
  subscriber: string;
  0: string;
}>;
export type SubscriptionChanged = ContractEventLog<{
  vcid: string;
  name: string;
  genRefTime: string;
  expiresAt: string;
  tier: string;
  deploymentSubset: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
  5: string;
}>;
export type Unlocked = ContractEventLog<{}>;
export type VcConfigRecordChanged = ContractEventLog<{
  vcid: string;
  key: string;
  value: string;
  0: string;
  1: string;
  2: string;
}>;
export type VcCreated = ContractEventLog<{
  vcid: string;
  owner: string;
  0: string;
  1: string;
}>;
export type VcOwnerChanged = ContractEventLog<{
  vcid: string;
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
  2: string;
}>;

export interface Subscriptions extends BaseContract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions): Subscriptions;
  clone(): Subscriptions;
  methods: {
    authorizedSubscribers(arg0: string): NonPayableTransactionObject<boolean>;

    /**
     * Allows the pendingFunctionalOwner address to finalize the transfer.
     */
    claimFunctionalOwnership(): NonPayableTransactionObject<void>;

    /**
     * Allows the pendingMigrationOwner address to finalize the transfer.
     */
    claimMigrationOwnership(): NonPayableTransactionObject<void>;

    erc20(): NonPayableTransactionObject<string>;

    /**
     * Returns the address of the current functionalOwner.
     */
    functionalOwner(): NonPayableTransactionObject<string>;

    genesisRefTimeDelay(): NonPayableTransactionObject<string>;

    getBootstrapRewardsWallet(): NonPayableTransactionObject<string>;

    getCertificationContract(): NonPayableTransactionObject<string>;

    getCommitteeContract(): NonPayableTransactionObject<string>;

    getDelegationsContract(): NonPayableTransactionObject<string>;

    getElectionsContract(): NonPayableTransactionObject<string>;

    getGuardiansRegistrationContract(): NonPayableTransactionObject<string>;

    getProtocolContract(): NonPayableTransactionObject<string>;

    getRewardsContract(): NonPayableTransactionObject<string>;

    getStakingContract(): NonPayableTransactionObject<string>;

    getStakingRewardsWallet(): NonPayableTransactionObject<string>;

    getSubscriptionsContract(): NonPayableTransactionObject<string>;

    /**
     * Returns true if the caller is the current functionalOwner.
     */
    isFunctionalOwner(): NonPayableTransactionObject<boolean>;

    /**
     * Returns true if the caller is the current migrationOwner.
     */
    isMigrationOwner(): NonPayableTransactionObject<boolean>;

    lock(): NonPayableTransactionObject<void>;

    locked(): NonPayableTransactionObject<boolean>;

    /**
     * Returns the address of the current migrationOwner.
     */
    migrationOwner(): NonPayableTransactionObject<string>;

    nextVcid(): NonPayableTransactionObject<string>;

    /**
     * Leaves the contract without functionalOwner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current functionalOwner.     * NOTE: Renouncing functionalOwnership will leave the contract without an functionalOwner, thereby removing any functionality that is only available to the functionalOwner.
     */
    renounceFunctionalOwnership(): NonPayableTransactionObject<void>;

    /**
     * Leaves the contract without migrationOwner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current migrationOwner.     * NOTE: Renouncing migrationOwnership will leave the contract without an migrationOwner, thereby removing any functionality that is only available to the migrationOwner.
     */
    renounceMigrationOwnership(): NonPayableTransactionObject<void>;

    setContractRegistry(_contractRegistry: string): NonPayableTransactionObject<void>;

    /**
     * Allows the current functionalOwner to set the pendingOwner address.
     * @param newFunctionalOwner The address to transfer functionalOwnership to.
     */
    transferFunctionalOwnership(newFunctionalOwner: string): NonPayableTransactionObject<void>;

    /**
     * Allows the current migrationOwner to set the pendingOwner address.
     * @param newMigrationOwner The address to transfer migrationOwnership to.
     */
    transferMigrationOwnership(newMigrationOwner: string): NonPayableTransactionObject<void>;

    unlock(): NonPayableTransactionObject<void>;

    virtualChains(
      arg0: number | string,
    ): NonPayableTransactionObject<{
      name: string;
      tier: string;
      rate: string;
      expiresAt: string;
      genRefTime: string;
      owner: string;
      deploymentSubset: string;
      isCertified: boolean;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: string;
      6: string;
      7: boolean;
    }>;

    setVcConfigRecord(vcid: number | string, key: string, value: string): NonPayableTransactionObject<void>;

    getVcConfigRecord(vcid: number | string, key: string): NonPayableTransactionObject<string>;

    addSubscriber(addr: string): NonPayableTransactionObject<void>;

    removeSubscriber(addr: string): NonPayableTransactionObject<void>;

    createVC(
      name: string,
      tier: string,
      rate: number | string,
      amount: number | string,
      owner: string,
      isCertified: boolean,
      deploymentSubset: string,
    ): NonPayableTransactionObject<{
      0: string;
      1: string;
    }>;

    extendSubscription(
      vcid: number | string,
      amount: number | string,
      payer: string,
    ): NonPayableTransactionObject<void>;

    setVcOwner(vcid: number | string, owner: string): NonPayableTransactionObject<void>;

    setGenesisRefTimeDelay(newGenesisRefTimeDelay: number | string): NonPayableTransactionObject<void>;

    getGenesisRefTimeDelay(): NonPayableTransactionObject<string>;

    getVcData(
      vcId: number | string,
    ): NonPayableTransactionObject<{
      name: string;
      tier: string;
      rate: string;
      expiresAt: string;
      genRefTime: string;
      owner: string;
      deploymentSubset: string;
      isCertified: boolean;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: string;
      6: string;
      7: boolean;
    }>;
  };
  events: {
    ContractRegistryAddressUpdated(cb?: Callback<ContractRegistryAddressUpdated>): EventEmitter;
    ContractRegistryAddressUpdated(options?: EventOptions, cb?: Callback<ContractRegistryAddressUpdated>): EventEmitter;

    FunctionalOwnershipTransferred(cb?: Callback<FunctionalOwnershipTransferred>): EventEmitter;
    FunctionalOwnershipTransferred(options?: EventOptions, cb?: Callback<FunctionalOwnershipTransferred>): EventEmitter;

    GenesisRefTimeDelayChanged(cb?: Callback<GenesisRefTimeDelayChanged>): EventEmitter;
    GenesisRefTimeDelayChanged(options?: EventOptions, cb?: Callback<GenesisRefTimeDelayChanged>): EventEmitter;

    Locked(cb?: Callback<Locked>): EventEmitter;
    Locked(options?: EventOptions, cb?: Callback<Locked>): EventEmitter;

    MigrationOwnershipTransferred(cb?: Callback<MigrationOwnershipTransferred>): EventEmitter;
    MigrationOwnershipTransferred(options?: EventOptions, cb?: Callback<MigrationOwnershipTransferred>): EventEmitter;

    Payment(cb?: Callback<Payment>): EventEmitter;
    Payment(options?: EventOptions, cb?: Callback<Payment>): EventEmitter;

    SubscriberAdded(cb?: Callback<SubscriberAdded>): EventEmitter;
    SubscriberAdded(options?: EventOptions, cb?: Callback<SubscriberAdded>): EventEmitter;

    SubscriberRemoved(cb?: Callback<SubscriberRemoved>): EventEmitter;
    SubscriberRemoved(options?: EventOptions, cb?: Callback<SubscriberRemoved>): EventEmitter;

    SubscriptionChanged(cb?: Callback<SubscriptionChanged>): EventEmitter;
    SubscriptionChanged(options?: EventOptions, cb?: Callback<SubscriptionChanged>): EventEmitter;

    Unlocked(cb?: Callback<Unlocked>): EventEmitter;
    Unlocked(options?: EventOptions, cb?: Callback<Unlocked>): EventEmitter;

    VcConfigRecordChanged(cb?: Callback<VcConfigRecordChanged>): EventEmitter;
    VcConfigRecordChanged(options?: EventOptions, cb?: Callback<VcConfigRecordChanged>): EventEmitter;

    VcCreated(cb?: Callback<VcCreated>): EventEmitter;
    VcCreated(options?: EventOptions, cb?: Callback<VcCreated>): EventEmitter;

    VcOwnerChanged(cb?: Callback<VcOwnerChanged>): EventEmitter;
    VcOwnerChanged(options?: EventOptions, cb?: Callback<VcOwnerChanged>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: 'ContractRegistryAddressUpdated', cb: Callback<ContractRegistryAddressUpdated>): void;
  once(
    event: 'ContractRegistryAddressUpdated',
    options: EventOptions,
    cb: Callback<ContractRegistryAddressUpdated>,
  ): void;

  once(event: 'FunctionalOwnershipTransferred', cb: Callback<FunctionalOwnershipTransferred>): void;
  once(
    event: 'FunctionalOwnershipTransferred',
    options: EventOptions,
    cb: Callback<FunctionalOwnershipTransferred>,
  ): void;

  once(event: 'GenesisRefTimeDelayChanged', cb: Callback<GenesisRefTimeDelayChanged>): void;
  once(event: 'GenesisRefTimeDelayChanged', options: EventOptions, cb: Callback<GenesisRefTimeDelayChanged>): void;

  once(event: 'Locked', cb: Callback<Locked>): void;
  once(event: 'Locked', options: EventOptions, cb: Callback<Locked>): void;

  once(event: 'MigrationOwnershipTransferred', cb: Callback<MigrationOwnershipTransferred>): void;
  once(
    event: 'MigrationOwnershipTransferred',
    options: EventOptions,
    cb: Callback<MigrationOwnershipTransferred>,
  ): void;

  once(event: 'Payment', cb: Callback<Payment>): void;
  once(event: 'Payment', options: EventOptions, cb: Callback<Payment>): void;

  once(event: 'SubscriberAdded', cb: Callback<SubscriberAdded>): void;
  once(event: 'SubscriberAdded', options: EventOptions, cb: Callback<SubscriberAdded>): void;

  once(event: 'SubscriberRemoved', cb: Callback<SubscriberRemoved>): void;
  once(event: 'SubscriberRemoved', options: EventOptions, cb: Callback<SubscriberRemoved>): void;

  once(event: 'SubscriptionChanged', cb: Callback<SubscriptionChanged>): void;
  once(event: 'SubscriptionChanged', options: EventOptions, cb: Callback<SubscriptionChanged>): void;

  once(event: 'Unlocked', cb: Callback<Unlocked>): void;
  once(event: 'Unlocked', options: EventOptions, cb: Callback<Unlocked>): void;

  once(event: 'VcConfigRecordChanged', cb: Callback<VcConfigRecordChanged>): void;
  once(event: 'VcConfigRecordChanged', options: EventOptions, cb: Callback<VcConfigRecordChanged>): void;

  once(event: 'VcCreated', cb: Callback<VcCreated>): void;
  once(event: 'VcCreated', options: EventOptions, cb: Callback<VcCreated>): void;

  once(event: 'VcOwnerChanged', cb: Callback<VcOwnerChanged>): void;
  once(event: 'VcOwnerChanged', options: EventOptions, cb: Callback<VcOwnerChanged>): void;
}
