export const sections = {
  api: 'api',
  orbsNodeStore: 'orbs node store',
  guardiansStore: 'guardians store',
  accountStore: 'account store',
  combinedEventsAndSubscriptions: 'combined events and subscriptions',
  approvableWizardStep: 'approvable wizard step',
  guardianChange: 'guardian change',
  restaking: 'restaking',
  rewardsClaiming: 'rewards claiming',
  guardianSelection: 'guardian selection',
  stakingAllowance: 'staking allowance',
  staking: 'staking',
  unstaking: 'unstaking',
  withdrawing: 'withdrawing',
};
